module Infor
  VERSION: String
  # See the writing guide of rbs: https://github.com/ruby/rbs#guides
  # 
  class Sysinfo
  end

  class Component
  end

  class Cpu
  end

  class Disk
  end

  class Network
  end

  class User
  end
end
